#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Parse time result generated by `time`.

Parse the real time from time result and get the average.

Usage: ./parse_time_log.py time_log_file

Output: each real time value, and finally the average value.
"""

import sys

def parse_time_log(infile):
    total_real_time = 0.0
    cnt = 0
    for line in infile.readlines():
        if line.startswith('real'):
            fields = line.split()
            exec_time = fields[1]
            minutes = 0
            seconds = 0.0
            if 'm' in exec_time:
                time_fields = exec_time.split('m') 
                minutes = int(time_fields[0])
                # remove the return and s
                seconds = float(time_fields[1][:-2])
            else:
                seconds = float(time_fields[1][:-2])
            real_time = 60 * minutes + seconds
            print(real_time)
            total_real_time += real_time
            cnt += 1
    print("avg: {}".format(total_real_time / cnt))
                

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("One argument: time_log_file")
    else:
        with open(sys.argv[1]) as infile:
            parse_time_log(infile) 
